stages:
  feature_extraction:
    cmd: ${python_interpreter_cmd} delius/feature_extraction.py
      --input_compressed_image_dir ${image_features.input_compressed_image_dir}
      --output_uncompressed_image_dir ${image_features.output_uncompressed_image_dir}
      --output_embedding_file ${image_features.output_embedding_file}
      --image_width ${image_features.image_width}
      --image_height ${image_features.image_height}
      --batch_size ${image_features.batch_size}
    deps:
    - ${image_features.input_compressed_image_dir}
    outs:
    - ${image_features.output_embedding_file}
  autoencoder_pretraining:
    cmd: ${python_interpreter_cmd} -m delius.autoencoder_pretraining
      --learning_rate ${training_hyperparameters.learning_rate}
      --epochs ${training_hyperparameters.num_epochs}
      --batch ${training_hyperparameters.batch_size}
      --encoder_hidden_dimensions ${encoder.hidden_dimensions}
      --input_embeddings_dimensions ${image_features.dimensions}
      --input_embeddings_file ${image_features.output_embedding_file}
      --output_encoder_file ${encoder.pretrained_path}
    deps:
    - delius/autoencoder_pretraining.py
    - ${image_features.output_embedding_file}
    outs:
    - ${encoder.pretrained_path}
  clustering_initialization:
    cmd: ${python_interpreter_cmd} -m delius.clustering_initialization
      --batch ${training_hyperparameters.batch_size}
      --encoder_hidden_dimensions ${encoder.hidden_dimensions}
      --input_embeddings_dimensions ${image_features.dimensions}
      --input_embeddings_file ${image_features.output_embedding_file}
      --input_pretrained_encoder ${encoder.pretrained_path}
      --output_centroids_file_path ${clustering.centroids_path}
      --n_clusters ${clustering.n_clusters}
    deps:
    - delius/clustering_initialization.py
    - ${image_features.output_embedding_file}
    - ${encoder.pretrained_path}
    outs:
    - ${clustering.centroids_path}