stages:
  feature_extraction:
    cmd: ${python_interpreter_cmd} delius/feature_extraction.py
      --input_compressed_image_dir ${image_features.input_compressed_image_dir}
      --output_uncompressed_image_dir ${image_features.output_uncompressed_image_dir}
      --output_embedding_file ${image_features.output_embedding_file}
      --image_width ${image_features.image_width}
      --image_height ${image_features.image_height}
      --batch_size ${image_features.batch_size}
    deps:
    - ${image_features.input_compressed_image_dir}
    outs:
    - ${image_features.output_embedding_file}