seed: 42

python_interpreter_cmd: python

images:
  compressed_image_dir: ./data/raw/images.tar.gz
  uncompressed_image_dir: ./data/interim/images/
  image_width: 224
  image_height: 224

image_features:
  embeddings_file: ./data/processed/embeddings.pth
  dimensions: 1024
  extraction:
    batch_size: 256

encoder:
  hidden_dimensions: 500 500 2000 10
  pretrained_path: ./models/pretrained/encoder.pth

hyperparameters:
  pretraining:
    batch_size: 256
    learning_rate: 1e-3
    num_epochs: 200
  clustering:
    batch_size: 256
    learning_rate: 1e-3
    n_clusters: 10
    steps: 8000
    update_interval: 140
    delta_tol: 0.001

clustering:
  centroids_path: ./models/kmeans/centroids.pth
  assignments_path: ./models/kmeans/assignments.pth
  dec_path: ./models/dec/dec.pth
  n_samples_per_cluster: 5
  embeddings_sample_franction: 0.1

env_file_path: '.env'
env_var_name:
  mlflow:
    runs:
      encoder_pretraining: ENCODER_PRETRAINING_MLFLOW_RUN_ID
      dec_fitting: DEC_FITTING_MLFLOW_RUN_ID