python_interpreter_cmd: python

image_features:
  input_compressed_image_dir: ./data/raw/images.tar.gz
  output_uncompressed_image_dir: ./data/interim/images/
  image_width: 224
  image_height: 224
  batch_size: 256
  output_embedding_file: ./data/processed/embeddings.pth

