python_interpreter_cmd: python

image_features:
  image_directory: /mnt/c/Users/Utente/Desktop/dl_case_study/images/images/imagesf2
  image_width: 224
  image_height: 224
  batch_size: 256
  output_file: ./data/processed/embeddings.pth

